class COLUMN:
    installers = ['FIRST NAME', 'LAST NAME', 'PHONE', 'EMAIL']
    jobs = ['JOB_ID', 'CUSTOMER', 'DESIGNER', 'INSTALLER', 'BOXES_IN', 'TOTAL_BOXES', 'BLINDS_ON_HAND', 'BLIND_COUNT', 'SCOPE', 'READY_TO_SCHEDULE']
    customers = ['F_NAME', 'L_NAME', 'ADDRESS', 'EMAIL', 'PHONE', 'AVAILABILITY', 'DESIGNER', 'JOB_ID']
    designers = ['F_NAME', 'L_NAME', 'EMAIL', 'PHONE', 'COMPANY', 'AREA']